<?php

namespace Database\Seeders;

use Faker\Generator;
use Illuminate\Container\Container;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * The current Faker instance.
     *
     * @var Generator
     */
    protected $faker;

    /**
     * Create a new seeder instance.
     *
     * @return void
     * @throws BindingResolutionException
     */
    public function __construct()
    {
        $this->faker = $this->withFaker();
    }

    /**
     * Get a new Faker instance.
     *
     * @return Generator
     * @throws BindingResolutionException
     */
    protected function withFaker(): Generator
    {
        return Container::getInstance()->make(Generator::class);
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => $this->faker->word(),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
            [
                'name' =>  Str::random(10),
                'labelMark' => $this->faker->text('5'),
                'description' => $this->faker->text('100'),
                'discount' => $this->faker->numberBetween(1, 99),
                'price' => $this->faker->randomFloat(2, 0, 10000),
                'code' => Str::random(10),
                'preview' => $this->faker->imageUrl(),
                'category_id' => $this->faker->numberBetween(1, 7),
                'promoCod' => null,
                'status' => 0,
                'quantity' => $this->faker->numberBetween(1, 99),
                'unit_of_measure' => $this->faker->numberBetween(1, 99),
                'images' => json_encode([
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                    $this->faker->imageUrl(),
                ]),
                'weight' => $this->faker->numberBetween(0, 5),
                'type' => 'box',
            ],
        ]);
    }
}
